version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      sigma:
        patterns: ["sigma-cli", "pySigma*", "pysigma*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        update-types: [minor, patch]
