"""Generate the ATT&CK coverage table in README.md and an ATT&CK Navigator layer from the rule tags."""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

from common import ROOT, Exclusion, Rule, load_rules, load_support

START = "<!-- coverage:start -->"
END = "<!-- coverage:end -->"
TECHNIQUE = re.compile(r"^attack\.(t\d{4}(?:\.\d{3})?)$")
LAYER_PATH = Path("coverage") / "attack-navigator.json"


def _techniques(rule: Rule) -> list[str]:
    return [m.group(1).upper() for t in rule.primary.get("tags") or [] if (m := TECHNIQUE.match(str(t)))]


def _tactics(rule: Rule) -> list[str]:
    return [
        str(t).removeprefix("attack.").replace("-", " ").title()
        for t in rule.primary.get("tags") or []
        if str(t).startswith("attack.") and not TECHNIQUE.match(str(t))
    ]


def _url(technique: str) -> str:
    return "https://attack.mitre.org/techniques/" + technique.replace(".", "/") + "/"


def render_table(rules: list[Rule], support: dict[tuple[str, str], Exclusion]) -> str:
    by_tech: dict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        for tech in _techniques(rule):
            by_tech[tech].append(rule)
    tactics = {t for r in rules for t in _tactics(r)}
    lines = [
        f"**{len(rules)} rules · {len(by_tech)} techniques · {len(tactics)} tactics** "
        "(generated by `scripts/attack_coverage.py` — do not edit)",
        "",
        "| Technique | Tactics | Rules | Not converted to |",
        "|---|---|---|---|",
    ]
    for tech in sorted(by_tech):
        tech_rules = by_tech[tech]
        tacs = sorted({t for r in tech_rules for t in _tactics(r)})
        titles = "<br>".join(r.primary["title"] for r in tech_rules)
        # One gap entry per rule, in the same order as the titles.
        gaps = "<br>".join(
            ", ".join(sorted(target for (slug, target) in support if slug == r.slug)) or "—" for r in tech_rules
        )
        lines.append(f"| [{tech}]({_url(tech)}) | {', '.join(tacs)} | {titles} | {gaps} |")
    return "\n".join(lines)


def navigator_layer(rules: list[Rule]) -> dict:
    by_tech: dict[str, list[str]] = defaultdict(list)
    for rule in rules:
        for tech in _techniques(rule):
            by_tech[tech].append(rule.primary["title"])
    return {
        "name": "Lab 06 detection-as-code coverage",
        "domain": "enterprise-attack",
        "versions": {"layer": "4.5"},
        "description": "Techniques covered by the Sigma rules in this repository (generated).",
        "techniques": [
            {"techniqueID": t, "score": 1, "comment": "; ".join(titles)} for t, titles in sorted(by_tech.items())
        ],
    }


def replace_block(text: str, block: str) -> str:
    if START not in text or END not in text:
        raise ValueError(f"README.md needs {START} and {END} markers")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n{block}\n{END}{tail}"


def run(root: Path, check: bool) -> list[str]:
    rules = load_rules(root / "rules")
    support = load_support(root / "support.yaml")
    readme = root / "README.md"
    layer = root / LAYER_PATH
    current = readme.read_text(encoding="utf-8")
    new_readme = replace_block(current, render_table(rules, support))
    new_layer = json.dumps(navigator_layer(rules), indent=2, ensure_ascii=False) + "\n"
    if check:
        errors = []
        if current != new_readme:
            errors.append("README.md coverage table is stale - run scripts/attack_coverage.py")
        if not layer.exists() or layer.read_text(encoding="utf-8") != new_layer:
            errors.append(f"{LAYER_PATH.as_posix()} is stale - run scripts/attack_coverage.py")
        return errors
    readme.write_text(new_readme, encoding="utf-8", newline="\n")
    layer.parent.mkdir(parents=True, exist_ok=True)
    layer.write_text(new_layer, encoding="utf-8", newline="\n")
    return []


def main() -> int:
    errors = run(ROOT, check="--check" in sys.argv[1:])
    for e in errors:
        print(e)
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
